name: Deploy to Netlify

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to netlify
      run: |
        npm install -g netlify-cli@23.7.3
        netlify deploy --dir=./src/ --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}